// High-performance image preloader and asset cache optimizer
export function preloadProductAssets() {
  if (typeof window === 'undefined') return;

  const priorityImages = [
    '/aa1.webp',
    '/aaa2.webp',
    '/aa2.webp',
    '/aa3.webp',
    '/aa4.webp',
    '/aa5.webp',
    '/aa1_thumb.webp',
    '/aaa2_thumb.webp',
    '/aa2_thumb.webp',
    '/aa3_thumb.webp',
    '/aa4_thumb.webp',
    '/aa5_thumb.webp',
    '/allure_gold_1.webp',
    '/allure_gold_2.webp',
    '/allure_gold_3.webp',
    '/allure_gold_4.webp',
    '/allure_gold_5.webp',
    '/allure_gold_1_thumb.webp',
    '/allure_gold_2_thumb.webp',
    '/allure_gold_3_thumb.webp',
    '/allure_gold_4_thumb.webp',
    '/allure_gold_5_thumb.webp',
    '/allure_gold_hero.webp',
    '/allure_gold_earrings.webp',
    '/allure_gold_model.webp',
    '/allure_gold_detail.webp',
    '/allure_gold_box.webp',
    '/Cinematic.webp',
    '/Hero_website.webp',
    '/Hero_website_neklace.webp',
    '/neklace_producshot.webp',
    '/neklace_productshot_2.webp',
    '/combo5_user_1.webp',
    '/combo5_user_2.webp',
    '/combo5_user_3.webp',
    '/combo5_user_4.webp',
    '/combo5_user_1_thumb.webp',
    '/elegant_combo_1.webp',
    '/elegant_combo_2.webp',
    '/elegant_combo_3.webp',
    '/elegant_combo_4.webp',
    '/elegant_combo_5.webp',
    '/elegant_combo_1_thumb.webp',
    '/elegant_combo_2_thumb.webp',
    '/elegant_combo_3_thumb.webp',
    '/elegant_combo_4_thumb.webp',
    '/elegant_combo_5_thumb.webp',
    '/radhika_ambani_1.webp',
    '/radhika_ambani_2.webp',
    '/radhika_ambani_3.webp',
    '/radhika_ambani_4.webp',
    '/radhika_ambani_5.webp',
    '/radhika_ambani_1_thumb.webp',
    '/radhika_ambani_2_thumb.webp',
    '/radhika_ambani_3_thumb.webp',
    '/radhika_ambani_4_thumb.webp',
    '/radhika_ambani_5_thumb.webp',
    '/radhika_green_hero.webp',
    '/radhika_green_detail.webp',
    '/radhika_green_earrings.webp',
    '/radhika_green_back.webp',
    '/radhika_green_lifestyle.webp',
    '/radhika_green_hero_thumb.webp',
    '/radhika_green_detail_thumb.webp',
    '/radhika_green_earrings_thumb.webp',
    '/radhika_green_back_thumb.webp',
    '/radhika_green_lifestyle_thumb.webp',
    '/Cinematic_thumb.webp',
    '/Hero_website_neklace_thumb.webp',
    '/neklace_producshot_thumb.webp',
    '/neklace_productshot_2_thumb.webp',
    '/c1.png',
    '/c1-1.png',
    '/c2.png',
    '/c3.png',
    '/c4.png',
    '/c5.png',
    '/c1_thumb.webp',
    '/c1-1_thumb.webp',
    '/c2_thumb.webp',
    '/c3_thumb.webp',
    '/c4_thumb.webp',
    '/c5_thumb.webp',
    '/b1.png',
    '/b2.png',
    '/b3.png',
    '/b4.png',
    '/b5.png',
    '/combo_2_aesthetic_hero.webp',
    '/combo_2_aesthetic_hero_thumb.webp',
    '/combo_2_aesthetic_green.webp',
    '/combo_2_aesthetic_green_thumb.webp',
    '/combo_2_aesthetic_pink.webp',
    '/combo_2_aesthetic_pink_thumb.webp',
    '/combo_2_aesthetic_model.webp',
    '/combo_2_aesthetic_model_thumb.webp',
    '/combo_2_aesthetic_flatlay.webp',
    '/combo_2_aesthetic_flatlay_thumb.webp',
    '/d1.png',
    '/d2.png',
    '/d3.png',
    '/d1.webp',
    '/d2.webp',
    '/d3.webp',
    '/d1_thumb.webp',
    '/d2_thumb.webp',
    '/d3_thumb.webp',
    '/emerald_snake_hero.webp',
    '/emerald_snake_chain.webp',
    '/emerald_snake_waterproof.webp',
    '/emerald_snake_model.webp',
    '/emerald_snake_box.webp',
    '/emerald_snake_hero_thumb.webp',
    '/emerald_snake_chain_thumb.webp',
    '/emerald_snake_waterproof_thumb.webp',
    '/emerald_snake_model_thumb.webp',
    '/emerald_snake_box_thumb.webp',
    '/UGC_1_thumb.webp',
    '/UGC_2_thumb.webp',
    '/UGC_3_thumb.webp',
    '/UGC_thumb.webp',
  ];

  const preheat = () => {
    priorityImages.forEach((src) => {
      const img = new Image();
      img.decoding = 'async';
      img.src = src;
    });
  };

  if ('requestIdleCallback' in window) {
    (window as Window & { requestIdleCallback: (cb: () => void) => void }).requestIdleCallback(preheat);
  } else {
    setTimeout(preheat, 150);
  }
}
